name: covid-drugs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - plotly
  - pandas
  - scipy
  - jupytext
  - nbconvert
  - tqdm
  - ipykernel
  - requests
